<Project>
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Library.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.Library.Sdk" Version="1.0.1-alpha.22.osoe-925" />

  <PropertyGroup>
    <Title>Lombiq Helpful Libraries - Refit Libraries for Orchard Core</Title>
    <CopyrightYear>2011</CopyrightYear>
    <DescriptionBody>Adds helpers for working with the Refit RESTful API consumer library. See the project website for detailed documentation.</DescriptionBody>
    <PackageTags>Lombiq;Refit;REST;RESTful;API</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Helpful-Libraries</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Helpful-Libraries/blob/dev/Lombiq.HelpfulLibraries.Refit/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit.HttpClientFactory" Version="11.2.0" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Library.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.Library.Sdk" Version="1.0.1-alpha.22.osoe-925" />
</Project>
