<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Helpful Libraries - Refit Libraries for Orchard Core</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2011, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Helpful Libraries - Refit Libraries for Orchard Core: Adds helpers for working with the Refit RESTful API consumer library. See the project website for detailed documentation.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>Lombiq;Refit;REST;RESTful;API</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Helpful-Libraries</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Helpful-Libraries/blob/dev/Lombiq.HelpfulLibraries.Refit/Readme.md</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Refit.HttpClientFactory" Version="10.0.1" />
  </ItemGroup>

</Project>
