<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\Utilities\Lombiq.MSBuild.Targets\Lombiq.MSBuild.Core.Targets\Lombiq.MSBuild.Core.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'"/>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.MSBuild.Core.Targets" Version="1.0.0-alpha.2.nest-643" />
  </ItemGroup>

  <PropertyGroup>
    <Title>Lombiq Helpful Libraries - Testing Libraries for Orchard Core</Title>
    <Copyright>Copyright © 2011, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Helpful Libraries - Testing Libraries for Orchard Core: Various useful libraries that can be handy when writing unit and integration tests for Orchard Core apps. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Moq;xUnit;UnitTesting;Testing</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Helpful-Libraries</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Helpful-Libraries/blob/dev/Lombiq.HelpfulLibraries.Testing/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq.AutoMock" Version="3.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
  </ItemGroup>

</Project>
