<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\Utilities\Lombiq.MSBuild.Targets\Lombiq.MSBuild.Core.Targets\Lombiq.MSBuild.Core.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'"/>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.MSBuild.Core.Targets" Version="1.0.0-alpha.2.nest-643" />
  </ItemGroup>

  <PropertyGroup>
    <Title>Lombiq Helpful Libraries - Command Line Libraries</Title>
    <Copyright>Copyright © 2011, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Helpful Libraries - Command Line Libraries. This project helps with executing command line calls. See the project website for detailed documentation.</Description>
    <PackageTags>Lombiq;cli;CliWrap</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Helpful-Libraries</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Helpful-Libraries/blob/dev/Lombiq.HelpfulLibraries.Cli/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.HelpfulLibraries.Common\Lombiq.HelpfulLibraries.Common.csproj" />
  </ItemGroup>

</Project>
