<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Readme.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.HelpfulLibraries.Samples\Lombiq.HelpfulLibraries.Samples.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\SimpleQuery.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>

</Project>
