<Project>
    <PropertyGroup>
      <TargetFramework>netstandard2.0</TargetFramework>
      <IsPackable>true</IsPackable>
      <Nullable>enable</Nullable>
      <LangVersion>14.0</LangVersion>
    </PropertyGroup>

    <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Library.Sdk/Sdk/Import.props" />
    <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.Library.Sdk" Version="1.0.1-alpha.15.osoe-1208" />

    <PropertyGroup>
        <Title>Lombiq Helpful Libraries - Attributes for Orchard Core</Title>
        <CopyrightYear>2011</CopyrightYear>
        <DescriptionBody>Adds attributes used by other projects. See the project website for detailed documentation.</DescriptionBody>
        <PackageTags>OrchardCore;Lombiq;Attributes</PackageTags>
        <RepositoryUrl>https://github.com/Lombiq/Helpful-Libraries</RepositoryUrl>
        <PackageProjectUrl>https://github.com/Lombiq/Helpful-Libraries/blob/dev/Lombiq.HelpfulLibraries.Attributes/Readme.md</PackageProjectUrl>
    </PropertyGroup>

    <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Library.Sdk/Sdk/Import.targets" />
    <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.Library.Sdk" Version="1.0.1-alpha.15.osoe-1208" />
</Project>
