<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\Utilities\Lombiq.MSBuild.Targets\Lombiq.MSBuild.Core.Targets\Lombiq.MSBuild.Core.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'"/>

  <PropertyGroup>
    <Title>Lombiq Helpful Libraries - Orchard Core Libraries</Title>
    <Copyright>Copyright © 2011, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Helpful Libraries - Orchard Core Libraries: Various useful libraries that can be handy when developing for Orchard Core, to be used from your own projects. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;YesSql;GraphQL;Liquid;DateTime;DependencyInjection</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Helpful-Libraries</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Helpful-Libraries/blob/dev/Lombiq.HelpfulLibraries.OrchardCore/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lombiq.MSBuild.Core.Targets" Version="1.0.0-alpha.1.nest-643" Condition="'$(NuGetBuild)' == 'true'" />
    <PackageReference Include="OrchardCore.Alias" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Autoroute" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ContentFields" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ContentManagement.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Search.Elasticsearch.Core" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Email.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.FileStorage.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Html" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Infrastructure" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Markdown" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Media.Core" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Queries" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Settings" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Setup.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Taxonomies" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Themes" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Title" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Users.Core" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Workflows.Abstractions" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <!-- Necessary so tag helpers will work in the projects depending on this. -->
  <ItemGroup>
    <PackageReference Include="OrchardCore.DisplayManagement" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.HelpfulLibraries.AspNetCore\Lombiq.HelpfulLibraries.AspNetCore.csproj" />
    <ProjectReference Include="..\Lombiq.HelpfulLibraries.Common\Lombiq.HelpfulLibraries.Common.csproj" />
  </ItemGroup>

</Project>
