<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.ContentFields" Version="2.1.0" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="2.1.0" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Autoroute" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.csproj" />
  </ItemGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true'" />

</Project>
