name: Publish to NuGet

on:
  push:
    tags:
      - v*

jobs:
  publish_nuget:
    name: Call publish workflow
    uses: Lombiq/GitHub-Actions/.github/workflows/publish-nuget.yml@dev
    secrets:
      API_KEY: ${{ secrets.DEFAULT_NUGET_PUBLISH_API_KEY }}
