name: Publish to NuGet

on:
  push:
    tags:
      - v*

jobs:
  call-publish-workflow:
    name: Call publish workflow
    uses: Lombiq/GitHub-Actions/.github/workflows/publish-nuget.yml@issue/OSOE-485
    secrets:
      API_KEY: ${{ secrets.DEFAULT_NUGET_PUBLISH_API_KEY }}
